/**
 * Application redux actions types
*/
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_LOADING_END = 'APP_LOADING_END';

export const APP_REFRESH_START = 'APP_REFRESH_START';
export const APP_REFRESH_END = 'APP_REFRESH_END';

export const SIGNED_IN = 'SIGNED_IN';
export const SIGNED_OUT = 'SIGNED_OUT';

export const SIGNING_IN = 'SIGNING_IN';
export const SIGNING_IN_COMPLETE = 'SINGING_IN_COMPLETE';


export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_PARTY = 'UPDATE_PARTY';

export const UPDATE_OVERVIEW_SUMMARY = 'UPDATE_OVERVIEW_SUMMARY';

export const UPDATE_TOTAL_SERVICE_REQUESTS_PER_JURISDICTION = 'UPDATE_TOTAL_SERVICE_REQUESTS_PER_JURISDICTION';
export const UPDATE_TOTAL_SERVICE_REQUESTS_PER_SERVICE_CATEGORY = 'UPDATE_TOTAL_SERVICE_REQUESTS_PER_SERVICE_CATEGORY';
export const UPDATE_TOTAL_SERVICE_REQUESTS_PER_SERVICE_GROUP = 'UPDATE_TOTAL_SERVICE_REQUESTS_PER_SERVICE_GROUP';
export const UPDATE_TOTAL_SERVICE_REQUESTS_PER_WORKSPACE = 'UPDATE_TOTAL_SERVICE_REQUESTS_PER_WORKSPACE';
export const UPDATE_TOTAL_SERVICE_REQUESTS_PER_METHOD = 'UPDATE_TOTAL_SERVICE_REQUESTS_PER_METHOD';

export const UPDATE_PENDING_SERVICE_REQUESTS_PER_JURISDICTION = 'UPDATE_PENDING_SERVICE_REQUESTS_PER_JURISDICTION';
export const UPDATE_PENDING_SERVICE_REQUESTS_PER_SERVICE_CATEGORY = 'UPDATE_PENDING_SERVICE_REQUESTS_PER_SERVICE_CATEGORY';
export const UPDATE_PENDING_SERVICE_REQUESTS_PER_SERVICE_GROUP = 'UPDATE_PENDING_SERVICE_REQUESTS_PER_SERVICE_GROUP';
export const UPDATE_PENDING_SERVICE_REQUESTS_PER_WORKSPACE = 'UPDATE_PENDING_SERVICE_REQUESTS_PER_WORKSPACE';
export const UPDATE_PENDING_SERVICE_REQUESTS_PER_METHOD = 'UPDATE_PENDING_SERVICE_REQUESTS_PER_METHOD';

export const UPDATE_RESOLVED_SERVICE_REQUESTS_PER_JURISDICTION = 'UPDATE_RESOLVED_SERVICE_REQUESTS_PER_JURISDICTION';
export const UPDATE_RESOLVED_SERVICE_REQUESTS_PER_SERVICE_CATEGORY = 'UPDATE_RESOLVED_SERVICE_REQUESTS_PER_SERVICE_CATEGORY';
export const UPDATE_RESOLVED_SERVICE_REQUESTS_PER_SERVICE_GROUP = 'UPDATE_RESOLVED_SERVICE_REQUESTS_PER_SERVICE_GROUP';
export const UPDATE_RESOLVED_SERVICE_REQUESTS_PER_WORKSPACE = 'UPDATE_RESOLVED_SERVICE_REQUESTS_PER_WORKSPACE';
export const UPDATE_RESOLVED_SERVICE_REQUESTS_PER_METHOD = 'UPDATE_RESOLVED_SERVICE_REQUESTS_PER_METHOD';

export const UPDATE_LATE_SERVICE_REQUESTS_PER_JURISDICTION = 'UPDATE_LATE_SERVICE_REQUESTS_PER_JURISDICTION';
export const UPDATE_LATE_SERVICE_REQUESTS_PER_SERVICE_CATEGORY = 'UPDATE_LATE_SERVICE_REQUESTS_PER_SERVICE_CATEGORY';
export const UPDATE_LATE_SERVICE_REQUESTS_PER_SERVICE_GROUP = 'UPDATE_LATE_SERVICE_REQUESTS_PER_SERVICE_GROUP';
export const UPDATE_LATE_SERVICE_REQUESTS_PER_WORKSPACE = 'UPDATE_LATE_SERVICE_REQUESTS_PER_WORKSPACE';
export const UPDATE_LATE_SERVICE_REQUESTS_PER_METHOD = 'UPDATE_LATE_SERVICE_REQUESTS_PER_METHOD';

export const UPDATE_AVERAGE_ATTEND_TIME_PER_JURISDICTIONS = 'UPDATE_AVERAGE_ATTEND_TIME_PER_JURISDICTIONS';
export const UPDATE_AVERAGE_ATTEND_TIME_PER_SERVICE_CATEGORIES = 'UPDATE_AVERAGE_ATTEND_TIME_PER_SERVICE_CATEGORIES';
export const UPDATE_AVERAGE_ATTEND_TIME_PER_SERVICE_GROUPS = 'UPDATE_AVERAGE_ATTEND_TIME_PER_SERVICE_GROUPS';
export const UPDATE_AVERAGE_ATTEND_TIME_PER_WORKSPACES = 'UPDATE_AVERAGE_ATTEND_TIME_PER_WORKSPACES';
export const UPDATE_AVERAGE_ATTEND_TIME_PER_METHODS = 'UPDATE_AVERAGE_ATTEND_TIME_PER_METHODS';

export const UPDATE_AVERAGE_RESOLVE_TIME_PER_JURISDICTIONS = 'UPDATE_AVERAGE_RESOLVE_TIME_PER_JURISDICTIONS';
export const UPDATE_AVERAGE_RESOLVE_TIME_PER_SERVICE_CATEGORIES = 'UPDATE_AVERAGE_RESOLVE_TIME_PER_SERVICE_CATEGORIES';
export const UPDATE_AVERAGE_RESOLVE_TIME_PER_SERVICE_GROUPS = 'UPDATE_AVERAGE_RESOLVE_TIME_PER_SERVICE_GROUPS';
export const UPDATE_AVERAGE_RESOLVE_TIME_PER_WORKSPACES = 'UPDATE_AVERAGE_RESOLVE_TIME_PER_WORKSPACES';
export const UPDATE_AVERAGE_RESOLVE_TIME_PER_METHODS = 'UPDATE_AVERAGE_RESOLVE_TIME_PER_METHODS';
